---
title: 'Project Proposal'
author: "Noam Hazan, Jacob Doh, Nicolas Halabi, Sebastian Naranjo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analysis of Income & Other Factors in Census Data

### Team Members

-   Noam Hazan
-   Jacob Doh
-   Nicolas Halabi

### Data Description

This project uses data from the US Census Bureau’s [American Community Survey (ACS) 5-Year Public Use Microdata Sample (2022)](https://data.census.gov/app/mdat/ACSPUMS5Y2022/vars). This dataset, which aggregates 60 months of collected data is separated by two levels, an individual and household layer which is a representation of the United States.

As a note, we were specific in choosing the 5 year estimate on account of the fact that it is the largest and most reliable sample size, and because for our analytic purposes precision is more important than currency.

The dataset is wide and unfocused, holding over 500 unique fields which cover anything from demographic, socioeconomic, housing, transportation, to anything else. The granularity of the de-identified dataset allows us to dive deeper into analysis on a per person basis, though geographical regions are restricted to areas of +100,000 or more people.

Linked is the [visual mapping](https://excalidraw.com/#json=OD2wml7I9-VxJzHTe5xwg,90lpGo5H8H9qnwsPCK-TGA) of the personal level of the dataset

### Initial Data Cleaning Steps

Some steps we might take to clean the data include the following:

-   Removing any obvious errors (e.g. full NA records, anomalous points)
-   Selecting variables that are important and not duplicates (see [mapping](https://excalidraw.com/#json=nNhOtRFMCZrkl-4_pEU60,DRY0GZ-frRMkWPj3vz_jOg)).
-   Filter down to relevant points (i.e. remove points that are irrelevant to our question)
    -   Filter down to relevant geographies
-   Map & translate numerical codes to their defined description (e.g. 1: "Male", 2: "Female")

### Basic/marginal summaries you have explored or plan to explore

Potential Ideas

-   Income, Assistance, & Work
    -   What is the relationship between people who get income assistance and hours worked? Do people that work more necessarily have a higher income or assistance rate?
    -   What factors are most influential to determine whether or not someone receives assistance? Are any demographics generally lower income and not receiving assistance?
    -   Are there certain factors that allow us to predict how far someone lives from their workplace? Does income play a role in peoples ability to live close to their home?

### Project idea / research questions:

**What are you trying to investigate?**

-   Income, Assistance, & Work
    -   Can we predict how demographic and socioeconomic factors influence individual income?

**What analyses or visualizations do you expect to use?**

-   Income, Assistance, & Work
    -   What factors influence individual income? Does education level significantly impact income? Are there differences in income across gender or employment status? Can we accurately predict income using demographic and socioeconomic variables?

### Supplemental Research - Existing Analysis

-   [Predicting Travel Mode of Individuals by Machine Learning (2015) [Hichem Omrani]](https://doi.org/10.1016/j.trpro.2015.09.037)

-   [Commuting by Public Transportation in the United States: 2019 - United States Census Report [Michael Burrows, Charlynn Burd, & Brian McKenzie]](https://www.census.gov/content/dam/Census/library/publications/2021/acs/acs-48.pdf)

-   [Data Analytics to Predict the Income and Economic Hierarchy on Census Data](https://doi.org/10.1109/CSITSS.2016.7779366)

    ### Sources

-   Dataset

    -   [American Community Survey (ACS) 5-Year Public Use Microdata Sample (2022)](https://data.census.gov/app/mdat/ACSPUMS5Y2022/vars)

-   Supplemental Dataset Information

    -   [American Community Survey 5-Year Data (2009-2024)](https://www.census.gov/data/developers/data-sets/acs-5year.2022.html#list-tab-1806015614)
    -   [Using 1-Year or 5-Year American Community Survey Data](https://www.census.gov/programs-surveys/acs/guidance/estimates.html#:~:text=Every%20community%20in%20the%20nation%20will%20continue,characteristics%20through%201%2Dyear%20and%205%2Dyear%20ACS%20products.)
    -   [PUMS Documentation](https://www.census.gov/programs-surveys/acs/microdata/documentation.2022.html#list-tab-1370939201)

-   [Mapping](https://excalidraw.com/#json=nNhOtRFMCZrkl-4_pEU60,DRY0GZ-frRMkWPj3vz_jOg)
